### ISSUE TITLE
好像没有用到在线识别的API

### ISSUE THREAD

**Issue by simeonwang** [ARC-MX/sgcc_electricity_new#1]
由于国家电网添加了滑动验证码登录验证，我这边采取了调用商业API的方式，没时间找靠谱的离线方案，（ddddocr识别准确率太低），如果后续找到靠谱的离线方案速度还可以的话我会考虑更新，暂时先这样吧。 在线验证API的注册地址http://www.ttshitu.com/user/soft.html，注册推荐码: [c611f7018fc74aa3b75c30584108c5c6 价格也不贵2块钱基本够大半年了。

**Comment by ARC-MX** [comment]
不好意思，文档没有更新，我已经换成了离线方案，利用神经网络检测，部署方案不变，方便大家使用，请熟悉
