### ISSUE TITLE
数据获取不完全

### ISSUE THREAD

**Issue by JedSunCN** [ARC-MX/sgcc_electricity_new#106]
LOG:
The current user xxxx data fetching failed 'DataFetcher' object has no attribute 'connect', the next user data will be fetched.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add initialization of the 'connect' attribute in the __init__ method of the DataFetcher class and update related methods to handle potential None values.

You can review changes in this commit: https://github.com/mark-addams001881/ARC-MX-sgcc_electricity_new-106/commit/d96975e3f109c0bb4db9bae9bce7a9d1b2df5fb1.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ARC-MX** [comment]
这个bug已经被修复过了，并不是数据获取不全，你可以更新镜像重试一下，如果你用不到数据库的情况下默认应当把设定ENABLE_DATABASE_STORAGE=False

**Comment by JedSunCN** [comment]
验证已解决，谢谢
