### ISSUE TITLE
按照示例添加实体报错

### ISSUE THREAD

**Issue by wjxyy** [ARC-MX/sgcc_electricity_new#13]
编辑/homeassistant/configuration.yaml文件，重启报错 Invalid config for 'template' at configuration.yaml, line 63: required key 'platform' not provided，
当前版本Core：2024.6.3
Supervisor：2024.06.0
Operating System：12.4
Frontend：20240610.1

**Comment by wjxyy** [comment]
大佬目前docker容器是正常运行也获取到了数据 
![image](https://github.com/ARC-MX/sgcc_electricity_new/assets/106721609/670eb5d4-0709-41f9-babe-7f0adf72f5b0)

**Comment by ARC-MX** [comment]
请参考文档，重新设置configuration，template下面是针对多用户的

**Comment by wjxyy** [comment]
大佬 请问修改的configuration 是项目中的 配置文件还是haos 中的配置文件，菜鸟刚接触，添麻烦了

**Comment by ARC-MX** [comment]
> 大佬 请问修改的configuration 是项目中的 配置文件还是haos 中的配置文件，菜鸟刚接触，添麻烦了

 homeassistant里面的配置文件相当于手动添加传感器

**Comment by wjxyy** [comment]
感谢大佬
