### ISSUE TITLE
为啥只能获取到T-2的日期消耗电量呢？想看昨日的如何查看呢？

### ISSUE THREAD

**Issue by DaPengBreakALeg** [ARC-MX/sgcc_electricity_new#14]

**Comment by ARC-MX** [comment]
你登录国家电网手动查看一下有没有T-2日的，国家电网垃圾网站时不时的就7-8天不更新用电情况，不是我这边的问题

**Comment by DaPengBreakALeg** [comment]
比如，今天28日，只能获取到26日的数据，但是我在网站上看，确实能看到27日的数据

**Comment by DaPengBreakALeg** [comment]
![Snipaste_2024-06-28_16-49-45](https://github.com/ARC-MX/sgcc_electricity_new/assets/58354685/ac84bcd2-c14f-4acf-889e-faac9f9795f3)
![8DC8AF18-84C5-480f-8C61-FA087F92062A](https://github.com/ARC-MX/sgcc_electricity_new/assets/58354685/9bef0e03-ff04-41e4-855d-2078753b6ecd)

**Comment by ARC-MX** [comment]
点一下那个近30天的数据，看一下

**Comment by DaPengBreakALeg** [comment]
![image](https://github.com/ARC-MX/sgcc_electricity_new/assets/58354685/8239c8eb-b6af-4e64-ad7b-42ed0a3c4a53)

**Comment by DaPengBreakALeg** [comment]
有没有可能，执行的时候，前一天的数据还没有正常刷新出来？

**Comment by ARC-MX** [comment]
> 有没有可能，执行的时候，前一天的数据还没有正常刷新出来？

大概率就是这样的，这个东西本质就是个爬虫，网站有什么，它就拿到什么数据，基本不会出错，但是至于网站上面数据什么时候更新可能是会有影响，这会你再重启一下容器看看日志。后面我看能不能一天执行两遍

**Comment by ARC-MX** [comment]
> 有没有可能，执行的时候，前一天的数据还没有正常刷新出来？

我出现过连续7天都没更新数据，我还纳闷为什么每天用电量这么一致，最后一看，直接无语了

**Comment by xiajingjie** [comment]
请问大佬不用docker的话，怎么本地化部署

> > 有没有可能，执行的时候，前一天的数据还没有正常刷新出来？
> 
> 我出现过连续7天都没更新数据，我还纳闷为什么每天用电量这么一致，最后一看，直接无语了

**Comment by DaPengBreakALeg** [comment]
> > 有没有可能，执行的时候，前一天的数据还没有正常刷新出来？
> 
> 大概率就是这样的，这个东西本质就是个爬虫，网站有什么，它就拿到什么数据，基本不会出错，但是至于网站上面数据什么时候更新可能是会有影响，这会你再重启一下容器看看日志。后面我看能不能一天执行两遍

确定了，就是这个问题

**Comment by DaPengBreakALeg** [comment]
感觉后续可以设置一天跑两次
