### ISSUE TITLE
docker打包优化探讨

### ISSUE THREAD

**Issue by navee** [ARC-MX/sgcc_electricity_new#19]
尝试把script打包到docker镜像，这样就不需要pull源码才能运行
想了解下不把script打包到镜像的原因
另外一个就是我打出来的镜像有1.3G，大出你打的包不少

**Comment by ARC-MX** [comment]
额，源码会变，镜像一般不会变动，后续稳定了可以考虑

**Comment by navee** [comment]
好吧，docker多层编译的情况下，镜像更新script只会拉取script层内容

**Comment by hehongbo** [comment]
如果您倾向不频繁构建Docker镜像，可以考虑把用于添加代码的 `COPY` 命令放在Dockerfile比较靠后的位置，例如倒数第二行（最后一行将会是 `CMD` 或 `ENTRYPOINT`），这样代码更新造成的镜像变动就会很小，如果用户没有prune掉原来的镜像，新的pull操作也只会拉取最后script这层变动的内容。

「整个Docker镜像提供完整的程序和入口点」显然比「只用Docker镜像提供带有无头Chromium浏览器的环境」要明朗且接近标准实践，用户也不再需要克隆仓库就能部署项目，同时也使项目的部署不再依赖Docker compose（项目现在已经不依赖Mongo，只编排一个容器确实有些没必要compose）

如果您乐意进一步讨论Dockerfile打包优化的话，我的另一个建议是用`ENV`语法去声明环境变量，这样更接近最佳实践也会让整套程序对图形前端的Docker更友好（例如NAS Web界面通常会把已声明的ENV显示出来让用户填写，或是由用户决定要不要覆盖默认值），当然不愿意在`docker run`命令中写大量`-e`参数的用户也可以继续使用env file（`docker run --envifile`）

被非技术背景的朋友喊来帮忙在他的NAS上部署这个项目，刚好看到这个问题于是前来写下自己的想法。

Thanks for the hard work and have a nice day.
