### ISSUE TITLE
新版NumPy报错

### ISSUE THREAD

**Issue by xuanvivo** [ARC-MX/sgcc_electricity_new#20]
sgcc_electricity  |
sgcc_electricity  | A module that was compiled using NumPy 1.x cannot be run in
sgcc_electricity  | NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
sgcc_electricity  | versions of NumPy, modules must be compiled with NumPy 2.0.
sgcc_electricity  | Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
sgcc_electricity  |
sgcc_electricity  | If you are a user of the module, the easiest solution will be to
sgcc_electricity  | downgrade to 'numpy<2' or try to upgrade the affected module.
sgcc_electricity  | We expect that some modules will need time to support NumPy 2.
sgcc_electricity  |
sgcc_electricity  | Traceback (most recent call last):  File "/app/main.py", line 13, in <module>
sgcc_electricity  |     from data_fetcher import DataFetcher
sgcc_electricity  |   File "/app/data_fetcher.py", line 29, in <module>
sgcc_electricity  |     from onnx import ONNX
sgcc_electricity  |   File "/app/onnx.py", line 4, in <module>
sgcc_electricity  |     import onnxruntime
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
sgcc_electricity  |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
sgcc_electricity  |     from .onnxruntime_pybind11_state import *  # noqa
sgcc_electricity  | AttributeError: _ARRAY_API not found
sgcc_electricity  | Traceback (most recent call last):
sgcc_electricity  |   File "/app/main.py", line 13, in <module>
sgcc_electricity  |     from data_fetcher import DataFetcher
sgcc_electricity  |   File "/app/data_fetcher.py", line 29, in <module>
sgcc_electricity  |     from onnx import ONNX
sgcc_electricity  |   File "/app/onnx.py", line 4, in <module>
sgcc_electricity  |     import onnxruntime
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 57, in <module>
sgcc_electricity  |     raise import_capi_exception
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
sgcc_electricity  |     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
sgcc_electricity  |   File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
sgcc_electricity  |     from .onnxruntime_pybind11_state import *  # noqa
sgcc_electricity  | ImportError
sgcc_electricity exited with code 0

**Comment by smilingpoplar** [comment]
把requirements.txt中的numpy注释打开

**Comment by smilingpoplar** [comment]
> 这个试过了 报一样的错

我更新了一下镜像，确实也报错，今天打包的两个版本都有问题。我回退到了镜像1.4.0。

@ARC-MX

**Comment by ARC-MX** [comment]
正在修复

**Comment by ARC-MX** [comment]
应该可以了，大家试一下

**Comment by smilingpoplar** [comment]
> v1.4.1没错吧

v1.4.1也是NumPy版本错误。
新的v1.4.2镜像没问题了。

注意到[这里](https://github.com/ARC-MX/sgcc_electricity_new/blob/cb87b6edb228586e840c60d8fc5aae9e748754d2/scripts/data_fetcher.py#L302)有个typo，字符串前忘加f""了。

**Comment by ARC-MX** [comment]
> 我猜是因为我没修改arcw/sgcc_electricity:latest

建议再试一下
