### ISSUE TITLE
V1.4.2编译启动报错

### ISSUE THREAD

**Issue by HiMyCocoo** [ARC-MX/sgcc_electricity_new#21]
麻烦大佬看下：

> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last):  File "/app/main.py", line 13, in <module>
>     from data_fetcher import DataFetcher
>   File "/app/data_fetcher.py", line 29, in <module>
>     from onnx import ONNX
>   File "/app/onnx.py", line 4, in <module>
>     import onnxruntime
>   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
>     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
>   File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
>     from .onnxruntime_pybind11_state import *  # noqa
> AttributeError: _ARRAY_API not found
> Traceback (most recent call last):
>   File "/app/main.py", line 13, in <module>
>     from data_fetcher import DataFetcher
>   File "/app/data_fetcher.py", line 29, in <module>
>     from onnx import ONNX
>   File "/app/onnx.py", line 4, in <module>
>     import onnxruntime
>   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 57, in <module>
>     raise import_capi_exception
>   File "/usr/local/lib/python3.9/site-packages/onnxruntime/__init__.py", line 23, in <module>
>     from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
>   File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/_pybind_state.py", line 32, in <module>
>     from .onnxruntime_pybind11_state import *  # noqa
> ImportError

**Comment by HiMyCocoo** [comment]
numpy已经安装1.X版本

root@ubuntu:~/sgcc_electricity_new# pipx install numpy==v1.26.4
⚠️  Note: f2py was already on your PATH at /usr/bin/f2py
  installed package numpy 1.26.4, installed using Python 3.12.3
  These apps are now globally available
    - f2py
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your
    PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file
    (i.e. ~/.bashrc).
done! ✨ 🌟 ✨

**Comment by MrChanning** [comment]
同样问题

**Comment by smilingpoplar** [comment]
`registry.cn-hangzhou.aliyuncs.com`的镜像还没同步？`docker.io`的可以

**Comment by HiMyCocoo** [comment]
> 同样问题

已解决，换成docker.io就可以

**Comment by ARC-MX** [comment]
重新打包上传了，之前误删了一个东西
