### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by mzoo-xyz** [ARC-MX/sgcc_electricity_new#3]
大佬，这个报错是怎么回事啊？
<html>
<body>

date | stream | content
-- | -- | --
2024/06/04 11:13:17 | stderr |  
2024/06/04 11:13:17 | stderr | onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./captcha.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version.
2024/06/04 11:13:17 | stderr | sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
2024/06/04 11:13:17 | stderr | File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session
2024/06/04 11:13:17 | stderr | self._create_inference_session(providers, provider_options, disabled_optimizers)
2024/06/04 11:13:17 | stderr | File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__
2024/06/04 11:13:17 | stderr | self.onnx_session = onnxruntime.InferenceSession(onnx_file_name)
2024/06/04 11:13:17 | stderr | File "/app/onnx.py", line 16, in __init__
2024/06/04 11:13:17 | stderr | self.onnx = ONNX("./captcha.onnx")
2024/06/04 11:13:17 | stderr | File "/app/data_fetcher.py", line 167, in __init__
2024/06/04 11:13:17 | stderr | fetcher = DataFetcher(PHONE_NUMBER, PASSWORD)
2024/06/04 11:13:17 | stderr | File "/app/main.py", line 37, in main
2024/06/04 11:13:17 | stderr | main()
2024/06/04 11:13:17 | stderr | File "/app/main.py", line 90, in <module>
2024/06/04 11:13:17 | stderr | Traceback (most recent call last):
2024/06/04 11:13:16 | stdout | 2024-06-04 11:13:16  [INFO    ] ---- 程序开始，当前仓库版本为1.3.3，仓库地址为https://github.com/ARC-MX/sgcc_electricity_new.git

</body>
</html>

**Comment by ARC-MX** [comment]
可能是昨天更新镜像版本问题，你重新更新一下镜像

**Comment by ARC-MX** [comment]
> 大佬，这个报错是怎么回事啊？
> 
> date | stream | content -- | -- | -- 2024/06/04 11:13:17 | stderr |   2024/06/04 11:13:17 | stderr | onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from ./captcha.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:111 onnxruntime::Model::Model(onnx::ModelProto&&, const PathString&, const IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&) Unknown model file format version. 2024/06/04 11:13:17 | stderr | sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model) 2024/06/04 11:13:17 | stderr | File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 310, in _create_inference_session 2024/06/04 11:13:17 | stderr | self._create_inference_session(providers, provider_options, disabled_optimizers) 2024/06/04 11:13:17 | stderr | File "/usr/local/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 283, in __init__ 2024/06/04 11:13:17 | stderr | self.onnx_session = onnxruntime.InferenceSession(onnx_file_name) 2024/06/04 11:13:17 | stderr | File "/app/onnx.py", line 16, in __init__ 2024/06/04 11:13:17 | stderr | self.onnx = ONNX("./captcha.onnx") 2024/06/04 11:13:17 | stderr | File "/app/data_fetcher.py", line 167, in __init__ 2024/06/04 11:13:17 | stderr | fetcher = DataFetcher(PHONE_NUMBER, PASSWORD) 2024/06/04 11:13:17 | stderr | File "/app/main.py", line 37, in main 2024/06/04 11:13:17 | stderr | main() 2024/06/04 11:13:17 | stderr | File "/app/main.py", line 90, in  2024/06/04 11:13:17 | stderr | Traceback (most recent call last): 2024/06/04 11:13:16 | stdout | 2024-06-04 11:13:16  [INFO    ] ---- 程序开始，当前仓库版本为1.3.3，仓库地址为https://github.com/ARC-MX/sgcc_electricity_new.git

可以了吗，可以就关闭这个issue

**Comment by mzoo-xyz** [comment]
嗯，可以了，谢谢大佬
