### ISSUE TITLE
运行NoneType报错

### ISSUE THREAD

**Issue by mzoo-xyz** [ARC-MX/sgcc_electricity_new#4]
麻烦大佬帮忙再看下这个报错

2024/06/04 14:29:52 | stderr | TypeError: cannot unpack non-iterable NoneType object
2024/06/04 14:29:52 | stderr | user_id_list, balance_list, last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list = data_fetcher.fetch()
2024/06/04 14:29:52 | stderr | File "/app/main.py", line 57, in run_task
2024/06/04 14:29:52 | stderr | Traceback (most recent call last):
2024/06/04 14:29:52 | stderr | TypeError: 'NoneType' object is not subscriptable
2024/06/04 14:29:52 | stdout | 2024-06-04 14:29:52  [ERROR   ] ---- state-refresh task failed, reason is cannot unpack non-iterable NoneType object
2024/06/04 14:29:52 | stdout | 2024-06-04 14:29:52  [ERROR   ] ---- Webdriver quit abnormly, reason: 'NoneType' object is not subscriptable. 5 retry times left.
2024/06/04 14:29:52 | stderr | month_list.append(month[-1])
2024/06/04 14:29:52 | stderr | File "/app/data_fetcher.py", line 430, in _get_other_data
2024/06/04 14:29:52 | stderr | last_daily_date_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list, month_list, month_usage_list, month_charge_list  = self._get_other_data(driver, user_id_list)
2024/06/04 14:29:52 | stderr | File "/app/data_fetcher.py", line 272, in _fetch
2024/06/04 14:29:52 | stderr | return self._fetch()
2024/06/04 14:29:52 | stderr | File "/app/data_fetcher.py", line 243, in fetch

**Comment by ARC-MX** [comment]
你是什么架构x86还是arm64，看样子应该是你没有国家电网的账号吧，先注册国家电网账户，绑定电表

**Comment by mzoo-xyz** [comment]
> 你是什么架构x86还是arm64，看样子应该是你没有国家电网的账号吧，先注册国家电网账户，绑定电表

我是x86的架构，也有国网的账号和户号，我账户里有8个户号，我估计是有的户号没有在使用，所以代码拿到为空值就报错了

**Comment by mzoo-xyz** [comment]
![Snipaste_2024-06-04_15-46-46](https://github.com/ARC-MX/sgcc_electricity_new/assets/39021125/9824285e-1efe-496f-ade4-f735e3be2dd1)

**Comment by ARC-MX** [comment]
有可能，多账户的问题我这没有环境调试
