### ISSUE TITLE
当获取用电量数据为空字符串时，转化float会出现错误

### ISSUE THREAD

**Issue by Javedhd** [ARC-MX/sgcc_electricity_new#58]
<img width="1437" alt="image" src="https://github.com/user-attachments/assets/31638e14-e73a-4153-ac70-bddf251fdf2a">

https://github.com/ARC-MX/sgcc_electricity_new/blob/3c354d3e183e2398c2cf90cbb30c641a90aae4a2/scripts/data_fetcher.py#L585

以上代码可放在try catch中捕获异常

**Comment by ARC-MX** [comment]
可以更新代码试试
