### ISSUE TITLE
麻烦大佬能不能在下版将月用电信息写进数据库

### ISSUE THREAD

**Issue by l58128667** [ARC-MX/sgcc_electricity_new#60]
麻烦大佬能不能在下版将月用电信息写进数据库，我尝试了几次改data_fetcher.py文件，都报错，感谢

**Comment by ARC-MX** [comment]
> 麻烦大佬能不能在下版将月用电信息写进数据库，我尝试了几次改data_fetcher.py文件，都报错，感谢

这有啥用呢，每天都记录了求和不就是月的么，当月没出来也不用记录呀
