### ISSUE TITLE
显示没有user_id_list

### ISSUE THREAD

**Issue by opersdev** [ARC-MX/sgcc_electricity_new#67]
显示登陆失败，但是又能获取用户ID，下面又显示没有user_id_list

**Comment by opersdev** [comment]
![Uploading e175190e-aae6-412c-a295-c9c4b5e9204a.png…]()

**Comment by opersdev** [comment]
![e175190e-aae6-412c-a295-c9c4b5e9204a](https://github.com/user-attachments/assets/ebb38e95-a82a-4bf7-86ac-a740df9d5886)

**Comment by ARC-MX** [comment]
手动登录国家电网官网看一下

**Comment by ARC-MX** [comment]
> ![e175190e-aae6-412c-a295-c9c4b5e9204a](https://private-user-images.githubusercontent.com/38125526/395832620-ebb38e95-a82a-4bf7-86ac-a740df9d5886.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNTU2ODEsIm5iZiI6MTczNDI1NTM4MSwicGF0aCI6Ii8zODEyNTUyNi8zOTU4MzI2MjAtZWJiMzhlOTUtYTgyYS00YmY3LTg2YWMtYTc0MGRmOWQ1ODg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDA5MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiMjAxNDNmZDAzNTJlNmQyZjg5NzI4NjU1ZWM4Y2E0YzhkMjAzNWExN2M1NTA3MmU1YzYwYTU5OTFlNTUyNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VtGIL5zK3OjnBAMzAnZDe8wdm4PdCnv0s-LR71HWTJo)

更新一下代码，再试一下
