### ISSUE TITLE
显示权限不够

### ISSUE THREAD

**Issue by pixotna** [ARC-MX/sgcc_electricity_new#68]
sgcc_electricity_new git:(master) ✗ docker-compose up --build
Starting sgcc_electricity ... 
Starting sgcc_electricity ... error

ERROR: for sgcc_electricity  Cannot start service app: error while creating mount source path '/root/sgcc_electricity_new/scripts': mkdir /root/sgcc_electricity_new: read-only file system

ERROR: for app  Cannot start service app: error while creating mount source path '/root/sgcc_electricity_new/scripts': mkdir /root/sgcc_electricity_new: read-only file system
ERROR: Encountered errors while bringing up the project.

root目录下权限全改成777了，还是不行，请教是怎么回事？

**Comment by ARC-MX** [comment]
更新一下代码，这和容器和代码无关，建议不要再root下面搞，docker-compose up就行
