### ISSUE TITLE
Docker正确启动日志报错，无法登录网站，env内用户名密码正确，请问可否解决？谢谢！

### ISSUE THREAD

**Issue by see2111** [ARC-MX/sgcc_electricity_new#71]
stdout: 2024-12-18 08:42:14  [INFO    ] ---- Webdriver initialized.
stderr: Traceback (most recent call last):
stderr:   File "/app/data_fetcher.py", line 242, in fetch
stderr:     return self._fetch()
stderr:   File "/app/data_fetcher.py", line 267, in _fetch
stderr:     if self._login(driver):
stderr:   File "/app/data_fetcher.py", line 307, in _login
stderr:     driver.get(LOGIN_URL)
stderr:   File "/usr/local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 621, in get_wrapped
stderr:     return orig_get(*args, **kwargs)
stderr:   File "/usr/local/lib/python3.9/site-packages/undetected_chromedriver/__init__.py", line 657, in get
stderr:     return super().get(url)
stderr:   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 441, in get
stderr:     self.execute(Command.GET, {'url': url})
stderr:   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
stderr:     self.error_handler.check_response(response)
stderr:   File "/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
stderr:     raise exception_class(message, screen, stacktrace)
stderr: selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED
stderr:   (Session info: chrome=120.0.6099.224)
stderr: Stacktrace:
stderr: #0 0x557324d51233 <unknown>
stderr: #1 0x557324a1b0fe <unknown>
stderr: #2 0x557324a13c66 <unknown>
stderr: #3 0x557324a05c05 <unknown>
stderr: #4 0x557324a07660 <unknown>
stderr: #5 0x557324a0612e <unknown>
stderr: #6 0x557324a04fd7 <unknown>
stderr: #7 0x557324a04e6c <unknown>
stderr: #8 0x557324a03943 <unknown>
stderr: #9 0x557324a03d94 <unknown>
stderr: #10 0x557324a1e662 <unknown>
stderr: #11 0x557324aafc56 <unknown>
stderr: #12 0x557324a92422 <unknown>
stderr: #13 0x557324aaf680 <unknown>
stderr: #14 0x557324a921a3 <unknown>
stderr: #15 0x557324a5713e <unknown>
stderr: #16 0x557324a58712 <unknown>
stderr: #17 0x557324d26534 <unknown>
stderr: #18 0x557324d29759 <unknown>
stderr: #19 0x557324d29238 <unknown>
stderr: #20 0x557324d29c05 <unknown>
stderr: #21 0x557324d18abf <unknown>
stderr: #22 0x557324d29f8e <unknown>
stderr: #23 0x557324d02c86 <unknown>
stderr: #24 0x557324d423e5 <unknown>
stderr: #25 0x557324d425cb <unknown>
stderr: #26 0x557324d507bf <unknown>
stderr: #27 0x7fadae3dbea7 start_thread
stderr: 
stdout: 2024-12-18 08:42:15  [ERROR   ] ---- Webdriver quit abnormly, reason: Message: unknown error: net::ERR_CONNECTION_REFUSED

**Comment by ARC-MX** [comment]
你这是你的docker网络配置有问题，不是我镜像的问题

**Comment by see2111** [comment]
更改网络配置后解决，感谢！
