### ISSUE TITLE
我的信息修改完了 但是没有输出那些信息  请问该怎么做 ？

### ISSUE THREAD

**Issue by dhf2587154870** [ARC-MX/sgcc_electricity_new#74]
WARN[0000] /root/sgcc_electricity_new/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 11/11
 ✔ app Pulled                                                                                                                                                                                             193.7s 
   ✔ 172514850d5c Pull complete                                                                                                                                                                            26.6s 
   ✔ f705a6b43696 Pull complete                                                                                                                                                                            27.5s 
   ✔ e97df099be36 Pull complete                                                                                                                                                                            30.7s 
   ✔ 8259fe043360 Pull complete                                                                                                                                                                            30.7s 
   ✔ 4628fa94c233 Pull complete                                                                                                                                                                            33.8s 
   ✔ 068b399bfbfb Pull complete                                                                                                                                                                            40.0s 
   ✔ 4f4fb700ef54 Pull complete                                                                                                                                                                            40.3s 
   ✔ 0c1ed6d647a0 Pull complete                                                                                                                                                                           130.2s 
   ✔ 0edc5ea743cd Pull complete                                                                                                                                                                           132.1s 
   ✔ 99fed26106a8 Pull complete                                                                                                                                                                           153.3s 
[+] Running 2/2
 ✔ Network sgcc_electricity_new_sgcc_network  Created                                                                                                                                                       0.4s 
 ✔ Container sgcc_electricity                 Started                                                                                                                                                       5.5s 
root@armbian:~/sgcc_electricity_new# /root/sgcc_electricity_new/docker-compose.yml
-bash: /root/sgcc_electricity_new/docker-compose.yml: 权限不够
root@armbian:~/sgcc_electricity_new# sudo /root/sgcc_electricity_new/docker-compose.yml
sudo: /root/sgcc_electricity_new/docker-compose.yml：找不到命令
root@armbian:~/sgcc_electricity_new# docker compose down
WARN[0000] /root/sgcc_electricity_new/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/2
 ✔ Container sgcc_electricity                 Removed                                                                                                                                                      10.6s 
 ✔ Network sgcc_electricity_new_sgcc_network  Removed                                                                                                                                                       0.5s 
root@armbian:~/sgcc_electricity_new# docker compose pull
WARN[0000] /root/sgcc_electricity_new/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Pulling 1/1

**Comment by ARC-MX** [comment]
建议补充一些基础知识呀，docker-compose up -d 是后台运行，看日志有别的命令

**Comment by dhf2587154870** [comment]
我都试过了两个命令 还是一倒验证码哪儿后面就挑了许多报错

ARCW ***@***.***>于2024年12月19日 周四18:40写道：
