### ISSUE TITLE
大佬这是咋回事……

### ISSUE THREAD

**Issue by gky008** [ARC-MX/sgcc_electricity_new#77]
看日志能获取到数据，但好像提取数据时出错
![Screenshot_2024-12-17-23-54-54-133_io homeassistant companion android](https://github.com/user-attachments/assets/a33b3d70-3bb8-4ae3-930e-5944f228d266)
![Screenshot_2024-12-17-23-55-08-252_io homeassistant companion android](https://github.com/user-attachments/assets/8521e65a-3ce2-4fa9-b889-4b8a25229e20)
![Screenshot_2024-12-17-23-55-32-015_io homeassistant companion android](https://github.com/user-attachments/assets/e944854c-6e3f-425d-9c25-3680a5c1cdaf)
![Screenshot_2024-12-17-23-55-45-009_io homeassistant companion android](https://github.com/user-attachments/assets/15dd7df1-4eca-4040-b1f2-83691c335ed0)

**Comment by ARC-MX** [comment]
你这日志咋看呀，起码搞个电脑端显示呢吧

**Comment by ARC-MX** [comment]
明天就好了，啥都不用管的
