### ISSUE TITLE
找不到实体

### ISSUE THREAD

**Issue by w0330t** [ARC-MX/sgcc_electricity_new#90]
我删掉了config里的配置，但是目前遇到另外一个问题，卡片直接找不到实体，然后能源里也找不到，但是在能源里能找到数据，在开发者工具中也找不到实体，我本来想把它删除掉然后重新等它推送，但是我找不到也没法删除。

![image](https://github.com/user-attachments/assets/b27e6517-e855-4fdd-b3bd-073fdf1f1c8e)
![image](https://github.com/user-attachments/assets/5cf00700-9d17-462d-bcb4-f46d9393910b)
![image](https://github.com/user-attachments/assets/4df3ff21-526c-498a-9c5a-a5dcf9332316)
![image](https://github.com/user-attachments/assets/88f3963a-db41-4be8-b15a-d4a21c3c871e)

**Comment by sulon007** [comment]
请问你是怎么配置ha的，docker里日志都正常，但ha里看不到任何数据

**Comment by w0330t** [comment]
> 请问你是怎么配置ha的，docker里日志都正常，但ha里看不到任何数据

作者之前给我说不用配置。但是目前我也没法展示。
能源面板你能找到这个实体吗？就是上面的第一张图那里

**Comment by carlchina** [comment]
我也遇到相同的问题 获取正常但是找不到实体。也找不到怎么在 HA 里面配置实体。

**Comment by sulon007** [comment]
> > 请问你是怎么配置ha的，docker里日志都正常，但ha里看不到任何数据
> 
> 作者之前给我说不用配置。但是目前我也没法展示。 能源面板你能找到这个实体吗？就是上面的第一张图那里
> 
> 今天倒是没有报错了，但是还是找不到实体，我都在考虑要不要进数据库把它删掉算了。 ![图片](https://private-user-images.githubusercontent.com/4970238/398508886-742fbc44-9ea8-4184-af28-320c706831a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTU4MTAsIm5iZiI6MTczNTExNTUxMCwicGF0aCI6Ii80OTcwMjM4LzM5ODUwODg4Ni03NDJmYmM0NC05ZWE4LTQxODQtYWYyOC0zMjBjNzA2ODMxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDgzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmZGVhNjJkZThjYTQ0NWM5YjBkNTE4NGQ1Y2E2NmVkZDk5MjgwY2UxMjIwYjAxNTc2ODg5OGY3ODU5ZGFjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZXDUXchVbeNgw0DRoPxUcKZRelvcB7e1qV3F8iuxwJU)

**我在能源面板中看不到任何实体**

**Comment by w0330t** [comment]
> > > 请问你是怎么配置ha的，docker里日志都正常，但ha里看不到任何数据
> > 
> > 
> > 作者之前给我说不用配置。但是目前我也没法展示。 能源面板你能找到这个实体吗？就是上面的第一张图那里
> > 今天倒是没有报错了，但是还是找不到实体，我都在考虑要不要进数据库把它删掉算了。 ![图片](https://private-user-images.githubusercontent.com/4970238/398508886-742fbc44-9ea8-4184-af28-320c706831a5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMTU4MTAsIm5iZiI6MTczNTExNTUxMCwicGF0aCI6Ii80OTcwMjM4LzM5ODUwODg4Ni03NDJmYmM0NC05ZWE4LTQxODQtYWYyOC0zMjBjNzA2ODMxYTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjVUMDgzMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTBmZGVhNjJkZThjYTQ0NWM5YjBkNTE4NGQ1Y2E2NmVkZDk5MjgwY2UxMjIwYjAxNTc2ODg5OGY3ODU5ZGFjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZXDUXchVbeNgw0DRoPxUcKZRelvcB7e1qV3F8iuxwJU)
> 
> **我在能源面板中看不到任何实体**

点那个添加用电数据，然后里面也没有东西吗？

**Comment by w0330t** [comment]
隔了几天突然找到了，不懂

**Comment by sulon007** [comment]
展示效果是什么样的呢
