### ISSUE TITLE
只有docker才能安装吗？

### ISSUE THREAD

**Issue by dldui-captain** [ARC-MX/sgcc_electricity_new#94]
新手前来咨询下，采用虚拟主机安装的supervisor版本，如何安装这个呢？无docker

**Comment by Qinggua64** [comment]
和你一样，虚拟机安装的。这个不知道怎么安装

**Comment by ARC-MX** [comment]
> 新手前来咨询下，采用虚拟主机安装的supervisor版本，如何安装这个呢？无docker

无docker你就装docker就行了，装完docker在安装这个
